### ISSUE TITLE
Confirm LST monthly dataset is indeed monthly and not daily units

### ISSUE THREAD

**Issue by kathrynberger** [developmentseed/geospatial-ds-cholera-lab#15]
LST data source: https://data.ceda.ac.uk/neodc/esacci/land_surface_temperature/data/MULTISENSOR_IRCDR/L3S/0.01/v2.00/monthly/ 

While the dataset description says monthly, and the file structure supports this - the file name is written in month, day, year format - and so want to verify 100% that there is not daily data in this LST product that will require further aggregation.

**Comment by kathrynberger** [comment]
According to the [Product User Guide](https://admin.climate.esa.int/media/documents/LST-CCI-D4.3-PUG_-_i2r0_-_Product_User_Guide.pdf) Table 1 the `MULTISENSOR_IRCDR_L3S_0.01 2.00` is available in both Daily and
Monthly (day
and night).

It would appear that the product we have selected as described in the [CEDA Data Catalog entry](ESA Land Surface Temperature Climate Change Initiative (LST_cci): **Monthly** Multisensor Infra-Red (IR) Low Earth Orbit (LEO) land surface temperature (LST) time series level 3 supercollated (L3S) global product (1995-2020), version 2.00) the unit of observation is `monthly`. 

Additionally, the catalog's description `Daytime and night-time temperatures are provided in separate files corresponding to 10:30 and 22:30 local solar time.` corresponds to that of the Product User Guide above (Monthly, day & night). This would suggest that the file name is an artifact of the fact that this data is also available in daily format.

**Comment by chuckwondo** [comment]
@kathrynberger, regarding `qual_flag`, I don't understand what this means:

> observation_proximity_to_local_time1_is_closest_observation

So, I don't know how to make use of that flag, do you?

**Comment by kathrynberger** [comment]
I have some assumptions around what that means, but will dig into the documentation to confirm. I'll respond here. 👍

**Comment by kathrynberger** [comment]
Copying the slack thread on discussion of how we might interpret that pixel quality flag [here](https://developmentseed.slack.com/archives/C025QMQED/p1695129289384489).
