### ISSUE TITLE
Confirm duplicate admin 2 geometries within outbreak dataset

### ISSUE THREAD

**Issue by kathrynberger** [developmentseed/geospatial-ds-cholera-lab#16]
There are 3 outbreak entries for 2 different districts in Benin that share the exact same admin 2 level geometry. We are assuming that this is an error. 

We will need to verify which, if any, geometry is valid for the 2 districts involved. (See @chuckwondo notebook for specifics on districts and outbreak number). 

If one geometry is valid, we will have to omit the other districts outbreak event from our database (as we cannot confirm which geometry it belongs to). 

If neither geometry is valid, we will have to omit both districts outbreak event values from our database.

**Comment by botanical** [comment]
For posterity, we confirmed that there were more than 2 duplicate geometries than we initially observed. Using [`drop_duplicates`](https://github.com/developmentseed/geospatial-ds-cholera-lab/blob/main/exploration/geolocate.ipynb), we were able to determine how many duplicate geometries we had. Now, we have 473 distinct regions to work with.
