### ISSUE TITLE
Define ML ready data format of combined outbreak and EO dataframes

### ISSUE THREAD

**Issue by kathrynberger** [developmentseed/geospatial-ds-cholera-lab#18]
In order to take advantage of both the temporal and spatial resolutions and have enough absence data points to create a binary (1 = outbreak, 0 = no outbreak) predictive classification model, I am proposing the following format for the final dataframe. This will be revised from earlier drafts of what the final table would look like (i.e., #3). 

In the table below `location_period_id` represents the key identifier for each of the adm2 districts . The `month` and `year` columns will refer to the "data cube" itself. In other words, we will have: 
* observations for each of the 3 variables (LST, Precipitation, Soil Moisture)
* observations for each of those 3 variables for the current month (m), and the 3 months prior (m-1; m-2, and m-3) to create lag variables for each
* This will sum to a total of 12 environmental columns (i.e., parameters) that will be put into the ML model

The binary `outbreak` column (1=outbreak happened, 2=no outbreak) will be the column we are predicting. Obviously, this will create an imbalanced dataset, for which there will be a separate issue to account for this in ML model preparation. 

See example final data frame (which will be a result of merging both the outbreak dataset at adm2 level and all of the zonal statistics provided for these districts over 10 years. (Table not full, because I became lazy creating pseudo data, but should give enough information to provide context) 👍 In other words, one can envision this dataframe being very long, instead of being very wide. Let me know if there are any questions. 
 
| **location_period_id** | **month** | **year** | **LST_m** | **LST_m-1** | **LST_m-2** | **LST_m-3** | **Precip_m** | **Precip_m-1** | **Precip_m-2** | **Precip_m-3** | **SM_m** | **SM_m-1** | **SM_m-2** | **SM_m-3** | **Outbreak** |
| --------------- | --------- | -------- | --------- | ----------- | ----------- | ----------- | ------------ | -------------- | -------------- | -------------- | -------- | ---------- | ---------- | ---------- | ------------ |
| A               | 1         | 2010     | 27.5      | 26.5        | 28          | 28.4        | 1.23         |                |                |                |          |            |            |            | 0            |
| A               | 2         | 2010     | 28.3      | 27.5        | 26.5        | 28          |              |                |                |                |          |            |            |            | 0            |
| A               | 3         | 2010     | 28.7      | 28.3        | 27.5        | 26.5        |              |                |                |                |          |            |            |            | 0            |
| A               | 4         | 2010     | 29.3      | 28.7        | 28.3        | 27.5        |              |                |                |                |          |            |            |            | 1            |
| A               | 5         | 2010     | 29.7      | 29.3        | 28.7        | 28.3        |              |                |                |                |          |            |            |            | 0            |
| A               | 6         | 2010     | 29.6      | 29.7        | 29.3        | 28.7        |              |                |                |                |          |            |            |            | 0            |
| A               | 7         | 2010     | 30.2      | 29.6        | 29.7        | 29.3        |              |                |                |                |          |            |            |            | 0            |
| A               | 8         | 2010     | 33.1      | 30.2        | 29.6        | 29.7        |              |                |                |                |          |            |            |            | 0            |
| A               | 9         | 2010     | 29.6      | 33.1        | 30.2        | 29.6        |              |                |                |                |          |            |            |            | 0            |
| A               | 10        | 2010     | 2.91      | 29.6        | 33.1        | 30.2        |              |                |                |                |          |            |            |            | 0            |
| A               | 11        | 2010     | 28.4      | 2.91        | 29.6        | 33.1        |              |                |                |                |          |            |            |            | 0            |
| A               | 12        | 2010     | 28.1      | 28.4        | 2.91        | 29.6        |              |                |                |                |          |            |            |            | 0            |
| A               | 1         | 2011     |           | 28.1        | 28.4        | 2.91        |              |                |                |                |          |            |            |            | 0            |
| A               | 2         | 2011     |           |             | 28.1        | 28.4        |              |                |                |                |          |            |            |            | 0            |
| A               | 3         | 2011     |           |             |             | 28.1        |              |                |                |                |          |            |            |            | 0            |
| A               | 4         | 2011     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| A               | 5         | 2011     |           |             |             |             |              |                |                |                |          |            |            |            |              |
| ...             | ...       | …        | …         | …           | …           | …           | …            | …              | …              | …              | …        | …          | …          | …          | …            |
| B               | 1         | 2010     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| B               | 2         | 2010     |           |             |             |             |              |                |                |                |          |            |            |            | 1            |
| B               | 3         | 2010     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| B               | 4         | 2010     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| B               | 5         | 2010     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| B               | 6         | 2010     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| B               | 7         | 2010     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| B               | 8         | 2010     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| B               | 9         | 2010     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| B               | 10        | 2010     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| B               | 11        | 2010     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| B               | 12        | 2010     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| B               | 1         | 2011     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| B               | 2         | 2011     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| B               | 3         | 2011     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| B               | 4         | 2011     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| B               | 5         | 2011     |           |             |             |             |              |                |                |                |          |            |            |            | 0            |
| …               | ...       | …        | …         | …           | …           | …           | …            | …              | …              | …              | …        | …          | …          | …          | …            |

cc' @chuckwondo @botanical

**Comment by chuckwondo** [comment]
@kathrynberger, for the outbreak column, @botanical and I are wondering if it should contain a 1 only when an outbreak _started_ in the month for that row. We suspect the answer is yes because we want to predict when an outbreak will start. If we put a 1 in the column for every month in which and outbreak was in progress, we suspect that would muddy the waters for the ML model, no?

**Comment by kathrynberger** [comment]
Yes @chuckwondo and @botanical, you're completely correct here. We would want to mark those outbreaks as 1 only if the outbreak _started_ that month for that row. Exactly as you have stated. By doing so the model we will develop will help us to answer the question of what environmental parameters are drivers of the cholera outbreak. 

If we were to express an outbreak = 1  for every month of the outbreak duration, we would be answering a different question.

You're completely right. In this example, we want to identify whether the environmental parameters we have selected have any influence over when an outbreak _started_. Great work 👍
