### ISSUE TITLE
Verify lat/long array for LST is consistent over time

### ISSUE THREAD

**Issue by kathrynberger** [developmentseed/geospatial-ds-cholera-lab#21]
Longitude and Latitude array that come back from year month LST dataset could be different which would impact our computation of `zones` for zonal statistics. If they are different, this would require recompute the zones for each year? 

Since we don't want to assume every monthly LST dataset will have the same set of lon/lat values, we will explore a random subset (e.g., 2-3) to make sure that the coordinates are identical.

**Comment by chuckwondo** [comment]
Addressed by #22
