### ISSUE TITLE
Run `zonal statistics` on monthly LST data for all districts for one year

### ISSUE THREAD

**Issue by kathrynberger** [developmentseed/geospatial-ds-cholera-lab#7]
Now that we've successfully performed zonal statistics on one monthly image of LST for all outbreak districts, we will want to run this process for a full year. This will be helpful to get an idea of processing time and identify any additional roadblocks (e.g., imputing missing data) that may be required to over come before running the preprocessing script on the full 10 years of data.

**Comment by chuckwondo** [comment]
Subsumed by #8
