### ISSUE TITLE
Run `zonal statistics` on monthly Precipitation data for all districts for one year

### ISSUE THREAD

**Issue by kathrynberger** [developmentseed/geospatial-ds-cholera-lab#9]
As we did for the LST data stream, we will need to perform zonal statistics on monthly precipitation data for all outbreak districts for a year.  Doing this for a year, will be helpful to get an idea of processing time and identify any additional roadblocks (e.g., imputing missing data) that may be required to over come before running the preprocessing script on the full 10 years of data.

**Comment by chuckwondo** [comment]
Subsumed by #10
